### PR TITLE
Remove the rhc-worker-playbook package

### LINKED ISSUE #16: remove rhc-worker-playbook rpm during install
On a RHEL 8.4 the following 2 RPM would already be installed

- rhc
- rhc-worker-playbook

When we activate the rhcd service in the customers environment for the catalog worker the playbook worker would also be activated and that VM would be targeted from the cloud to run insights playbook.

Since we only need the catalog worker we should remove the play book worker by removing the rhc-worker-playbook RPM during our install.

### PR DESCRIPTION
**Pull request by mkanoor**
Fixes #16

### CODE REVIEW

**Comment by mkanoor** [comment]
@Spredzy Please review

**Review by Spredzy — CHANGES_REQUESTED** [review]
This is a packaging isssue. This sshould be solved at the spec level[1] as explained in https://github.com/ansible/automation_services_catalog_client/issues/16 

[1] https://code.engineering.redhat.com/gerrit/c/ansible-automation-platform/rpms/+/240751

**Comment by mkanoor** [comment]
@Spredzy This is not a packaging issue it is a configuration issue. Some customers might be ok with running both the workers others might not want the playbook worker. By making it a configurable parameter the customer can decide if they want to use both the workers or just the catalog worker. If we don't make this change the customer would be running both the workers. Our change makes it configurable.

If we go the other way of removing the rhc-worker-playbook in the rpm spec file we would have to distribute 2 different RPM's one for one set of customers who want both the workers and another rpm for customers that only want the catalog worker.

**Review by Spredzy — APPROVED** [review]
Thanks for explanation. Looks good then.

**Pull request merged**
